'use client';

import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import { Chatbot } from '@/components/Chatbot';
import { ThemeToggle } from '@/components/ThemeToggle';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={`${inter.className} bg-white dark:bg-gray-900 text-gray-900 dark:text-white min-h-screen transition-colors duration-200`}>
        <ThemeToggle />
        {children}
        <Chatbot />
      </body>
    </html>
  );
}
